<a href="https://colab.research.google.com/github/chauhanmuskan291980-wq/Deep_learning_project_by_RNN/blob/main/Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
      'the glass of juice',
        'the cup if tea',
        'I am a good boy',
        'understand the meaning of words',
        'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup if tea',
 'I am a good boy',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [9]:
one_hot_repr = [one_hot(words , voc_size) for words in sent]
one_hot_repr

[[7034, 8369, 9657, 3334],
 [7034, 8369, 9657, 7996],
 [7034, 8559, 9917, 8811],
 [6165, 2021, 5879, 6605, 7048],
 [1202, 7034, 8114, 9657, 4122],
 [5500, 1528, 5936, 6605]]

In [10]:
## word embedding Representataion
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [13]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr , padding='pre' , maxlen=sent_length )
embedding_docs

array([[   0,    0,    0,    0, 7034, 8369, 9657, 3334],
       [   0,    0,    0,    0, 7034, 8369, 9657, 7996],
       [   0,    0,    0,    0, 7034, 8559, 9917, 8811],
       [   0,    0,    0, 6165, 2021, 5879, 6605, 7048],
       [   0,    0,    0, 1202, 7034, 8114, 9657, 4122],
       [   0,    0,    0,    0, 5500, 1528, 5936, 6605]], dtype=int32)

In [20]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim))
model.build(input_shape=(None, sent_length))
model.compile(optimizer='adam', loss='mse')

In [21]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step


array([[[ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [-0.0337434 ,  0.03212506,  0.03099478, -0.03595446,
          0.02706725, -0.01050131, -0.04083475,  0.02414193,
          0.03624896, -0.01237527],
        [-0.00487689,  0.01293205, -0.04238559, -0.00382341,
          0.0136559 , -0.00428128, -0.02659589,  0.0084838 ,
         -0.04767027, -0.02286779],
        [ 0.01395446, -0.0092921 , -0.02993035,  0.0

In [25]:
embedding_docs[0]

array([   0,    0,    0,    0, 7034, 8369, 9657, 3334], dtype=int32)

In [31]:
import numpy as np

embedding_docs = np.array(embedding_docs)
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [ 0.0111933 , -0.0333135 ,  0.00950555,  0.01354719,
         -0.0118238 , -0.02647452,  0.03311617, -0.00774889,
          0.03727615,  0.00362469],
        [-0.0337434 ,  0.03212506,  0.03099478, -0.03595446,
          0.02706725, -0.01050131, -0.04083475,  0.02414193,
          0.03624896, -0.01237527],
        [-0.00487689,  0.01293205, -0.04238559, -0.00382341,
          0.0136559 , -0.00428128, -0.02659589,  0.0084838 ,
         -0.04767027, -0.02286779],
        [ 0.01395446, -0.0092921 , -0.02993035,  0.0